// 12개의 질문을 포함한 하나의 배열!
export const questioncontent = [
  {
    number: 1,
    question: "Trong một bữa tiệc, bạn sẽ",
    answer1: "Tương tác với nhiều người, kể cả người lạ",
    answer2: "Tương tác với một số ít người mà bạn biết",
    type: "E",
  },
  {
    number: 2,
    question: "Bạn là người",
    answer1: "Thực tế hơn là suy đoán",
    answer2: "Suy đoán hơn là thực tế",
    type: "S",
  },
  {
    number: 3,
    question: "Tình huống nào khiến bạn cảm thấy tệ hơn?",
    answer1: "Mọi thứ mông lung, không thực tế",
    answer2: "Nhàm chán, đơn điệu, lặp đi lặp lại",
    type: "T",
  },
  {
    number: 4,
    question: "Bạn thấy ấn tượng bởi",
    answer1: "Nguyên lý, nguyên tắc",
    answer2: "Cảm xúc, tình cảm",
    type: "F",
  },
  {
    number: 5,
    question: "Bạn có xu hướng nghiêng về",
    answer1: "Những gì có tính thuyết phục",
    answer2: "Những gì cảm động",
    type: "J",
  },
  {
    number: 6,
    question: "Bạn thích làm việc theo cách nào?",
    answer1: "Theo deadlines",
    answer2: "Tùy hứng",
    type: "P",
  },
  {
    number: 7,
    question: "Bạn có xu hướng lựa chọn",
    answer1: "Khá cẩn thận, xem xét kĩ lưỡng",
    answer2: "Tin vào cảm giác lúc lựa chọn",
    type: "E",
  },
  {
    number: 8,
    question: "Tại các buổi gặp mặt, bạn sẽ",
    answer1: "Ở lại đến cuối buổi, càng lúc càng phấn khích",
    answer2: "Ra về sớm và cảm thấy mệt",
    type: "S",
  },
  {
    number: 9,
    question: "Tuýp người nào sẽ thu hút bạn hơn?",
    answer1: "Người nhạy cảm",
    answer2: "Người giàu trí tưởng tượng",
    type: "N",
  },
  {
    number: 10,
    question: "Bạn hứng thú hơn với",
    answer1: "Những việc thực tế xảy ra",
    answer2: "Những việc có khả năng xảy ra",
    type: "F",
  },
  {
    number: 11,
    question: "Khi đánh giá người khác, bạn thường",
    answer1: "Dựa trên các quy định, luật lệ",
    answer2: "Dựa trên hoàn cảnh cụ thể",
    type: "T",
  },
  {
    number: 12,
    question: "Khi tiếp cận người khác, bạn nghiêng về",
    answer1: "Tiếp cận khách quan",
    answer2: "Tiếp cận cá nhân",
    type: "J",
  },
  {
    number: 13,
    question: "Bạn là người",
    answer1: "Đúng giờ",
    answer2: "Nhàn nhã, thoải mái",
    type: "P",
  },
  {
    number: 14,
    question: "Bạn cảm thấy bồn chồn khi có những việc",
    answer1: "Chưa hoàn thành",
    answer2: "Đã hoàn thành",
    type: "J",
  },
  {
    number: 15,
    question: "Trong một nhóm thì bạn là người",
    answer1: "Luôn nắm bắt kịp thời thông tin về các vấn đề của mọi người",
    answer2: "Thường biết thông tin sau",
    type: "E",
  },
  {
    number: 16,
    question: "Với các công việc thông thường, bạn nghiêng về cách",
    answer1: "Làm theo cách thông thường",
    answer2: "Làm theo cách của riêng mình",
    type: "S",
  },
  {
    number: 17,
    question: "Theo bạn, các nhà văn nên",
    answer1: "Viết những gì họ nghĩ, và nghĩ những gì họ viết, một cách rõ ràng",
    answer2: "Diễn đạt sự việc bằng cách so sánh, liên tưởng",
    type: "N",
  },
  {
    number: 18,
    question: "Điều gì lôi cuốn bạn hơn",
    answer1: "Sự nhất quán về tư duy, suy nghĩ",
    answer2: "Sự hòa hợp trong các mối quan hệ con người",
    type: "F",
  },
  {
    number: 19,
    question: "Bạn cảm thấy thoải mái hơn khi đưa ra nhận xét",
    answer1: "Một cách logic",
    answer2: "Một cách có ý nghĩa, có giá trị",
    type: "T",
  },
  {
    number: 20,
    question: "Bạn thích những điều",
    answer1: "Đã được định trước",
    answer2: "Chưa được quyết định",
    type: "J",
  },
  {
    number: 21,
    question: "Bạn là người",
    answer1: "Nghiêm túc và quyết đoán",
    answer2: "Dễ tính, thoải mái",
    type: "P",
  },
  {
    number: 22,
    question: "Khi nói chuyện điện thoại, bạn",
    answer1: "Hiếm khi băn khoăn đến những điều mình sẽ nói",
    answer2: "Thường chuẩn bị trước những điều mình sẽ nói",
    type: "E",
  },
  {
    number: 23,
    question: "Theo bạn, 'các sự việc, sự kiện'",
    answer1: "'Bản thân nó giải thích cho chính nó'",
    answer2: "Nó là bằng chứng giải thích cho các quy tắc, quy luật",
    type: "S",
  },
  {
    number: 24,
    question: "Theo bạn, những người có tầm nhìn xa",
    answer1: "Ở mức độ nào đó, họ thường gây khó chịu cho người khác",
    answer2: "Khá thú vị, hấp dẫn",
    type: "N",
  },
  {
    number: 25,
    question: "Bạn là người",
    answer1: "Có cái đầu lạnh",
    answer2: "Có trái tim ấm",
    type: "F",
  },
  {
    number: 26,
    question: "Theo bạn, điều nào tồi tệ hơn",
    answer1: "Không công bằng",
    answer2: "Tàn nhẫn",
    type: "T",
  },
  {
    number: 27,
    question: "Mọi người nên để các sự kiện xảy ra",
    answer1: "Theo hướng lựa chọn và cân nhắc kĩ lưỡng",
    answer2: "Diễn ra ngẫu nhiên, tự nhiên, tình cờ",
    type: "J",
  },
  {
    number: 28,
    question: "Bạn cảm thấy thoải mái hơn khi",
    answer1: "Đã mua một thứ gì đó",
    answer2: "Có khả năng và có sự lựa chọn để mua",
    type: "P",
  },
  {
    number: 29,
    question: "Trong công ty, bạn là người",
    answer1: "Bắt đầu một cuộc trò chuyện",
    answer2: "Chờ đợi người khác bắt chuyện",
    type: "E",
  },
  {
    number: 30,
    question: "Những logic được mọi người chấp nhận, bạn sẽ",
    answer1: "Tin tưởng vào những điều đó và hiếm khi nghi ngờ, đặt câu hỏi",
    answer2: "Xem xét lại tính đúng đắn của những điều đó và đặt câu hỏi",
    type: "N",
  },
  {
    number: 31,
    question: "Theo bạn, trẻ em thường không",
    answer1: "Tự mình phát huy hết năng lực",
    answer2: "Thỏa mãn hết trí tưởng tượng của mình",
    type: "J",
  },
  {
    number: 32,
    question: "Khi đưa ra các quyết định, bạn thiên về",
    answer1: "Các tiêu chuẩn, quy định",
    answer2: "Cảm xúc, cảm nhận",
    type: "F",
  },
  {
    number: 33,
    question: "Bạn nghiêng về tính cách",
    answer1: "Kiên quyết, cứng rắn hơn là nhẹ nhàng",
    answer2: "Nhẹ nhàng hơn là kiên quyết, cứng rắn",
    type: "T",
  },
  {
    number: 34,
    question: "Theo bạn, khả năng nào đáng ngưỡng mộ hơn",
    answer1: "Khả năng tổ chức và làm việc có phương pháp",
    answer2: "Khả năng thích ứng và xoay xở trước mọi tình huống",
    type: "P",
  },
  {
    number: 35,
    question: "Bạn đề cao",
    answer1: "Sự chắc chắn",
    answer2: "Sự cởi mở",
    type: "J",
  },
  {
    number: 36,
    question: "Đối mặt với những vấn đề mới, bạn thường",
    answer1: "Thấy kích thích và hào hứng",
    answer2: "Cảm thấy mệt mỏi",
    type: "N",
  },
  {
    number: 37,
    question: "Thường thì bạn là",
    answer1: "Người thực tế",
    answer2: "Người có trí tưởng tượng phong phú",
    type: "S",
  },
  {
    number: 38,
    question: "Bạn thường có xu hướng",
    answer1: "Xem những người khác hữu ích như thế nào",
    answer2: "Xem người khác nghĩ và cảm nhận như thế nào",
    type: "T",
  },
  {
    number: 39,
    question: "Bạn cảm thấy thoải mái hơn khi",
    answer1: "Thảo luận một vấn đề kĩ lưỡng, triệt để",
    answer2: "Đạt được thỏa thuận, sự nhất trí về vấn đề",
    type: "F",
  },
  {
    number: 40,
    question: "Theo bạn, cái nào chi phối bạn nhiều hơn",
    answer1: "Cái đầu",
    answer2: "Trái tim",
    type: "T",
  },
  {
    number: 41,
    question: "Bạn thích kiểu công việc",
    answer1: "Được giao trọn gói, hoàn thành rồi mới bàn giao",
    answer2: "Công việc làm hàng ngày, theo lịch",
    type: "J",
  },
  {
    number: 42,
    question: "Bạn có xu hướng tìm kiếm những điều",
    answer1: "Theo trật tự, thứ tự",
    answer2: "Ngẫu nhiên, tình cờ",
    type: "P",
  },
  {
    number: 43,
    question: "Bạn thích kiểu nào hơn",
    answer1: "Nhiều bạn bè ở mức độ xã giao, ít thân thiết",
    answer2: "Một vài người bạn thân với mức độ thân thiết cao",
    type: "E",
  },
  {
    number: 44,
    question: "Bạn thường dựa vào",
    answer1: "Sự kiện, thông tin",
    answer2: "Nguyên lí, nguyên tắc",
    type: "S",
  },
  {
    number: 45,
    question: "Bạn hứng thú với việc",
    answer1: "Sản xuất và phân phối",
    answer2: "Thiết kế, nghiên cứu",
    type: "N",
  },
  {
    number: 46,
    question: "Bạn thích được khen là",
    answer1: "Một người có logic rất tốt",
    answer2: "Một người rất tình cảm, tinh tế",
    type: "F",
  },
  {
    number: 47,
    question: "Bạn thấy điều nào ở mình giá trị hơn",
    answer1: "Kiên định, vững vàng",
    answer2: "Toàn tâm, cống hiến",
    type: "J",
  },
  {
    number: 48,
    question: "Bạn thường thích",
    answer1: "Một tuyên bố cuối cùng, không thay đổi",
    answer2: "Một tuyên bố dự kiến, ban đầu",
    type: "J",
  },
  {
    number: 49,
    question: "Bạn thấy thoải mái hơn",
    answer1: "Trước khi đưa ra quyết định",
    answer2: "Sau khi đưa ra quyết định",
    type: "P",
  },
  {
    number: 50,
    question: "Bạn là người",
    answer1: "Dễ dàng bắt chuyện và nói chuyện lâu dài với người lạ",
    answer2: "Có ít điều để nói với người lạ",
    type: "E",
  },
  {
    number: 51,
    question: "Bạn có xu hướng tin tưởng vào",
    answer1: "Kinh nghiệm của mình",
    answer2: "Linh cảm của mình",
    type: "S",
  },
  {
    number: 52,
    question: "Bạn thấy mình là người như thế nào?",
    answer1: "Là người thực tế hơn là khéo léo, mưu trí",
    answer2: "Là người khéo léo, mưu trí hơn là thực tế",
    type: "N",
  },
  {
    number: 53,
    question: "Theo bạn, ai là người xứng đáng được khen ngợi",
    answer1: "Một người giàu lý trí",
    answer2: "Một người giàu cảm xúc",
    type: "T",
  },
  {
    number: 54,
    question: "Bạn có xu hướng là người",
    answer1: "Công bằng, vô tư",
    answer2: "Thông cảm, đồng cảm",
    type: "F",
  },
  {
    number: 55,
    question: "Mọi việc sẽ hợp lý, tốt hơn nếu",
    answer1: "Được chuẩn bị trước",
    answer2: "Diễn ra tự nhiên",
    type: "J",
  },
  {
    number: 56,
    question: "Trong các mối quan hệ, hầu hết mọi việc nên",
    answer1: "Nói chuyện để thương lượng, giải quyết",
    answer2: "Diễn ra ngẫu nhiên theo điều kiện hoàn cảnh",
    type: "P",
  },
  {
    number: 57,
    question: "Khi chuông điện thoại reo, bạn sẽ",
    answer1: "Là người đầu tiên nhấc máy để nghe",
    answer2: "Hi vọng có người khác sẽ nhấc máy",
    type: "E",
  },
  {
    number: 58,
    question: "Bạn đánh giá cao điều gì ở bản thân mình hơn",
    answer1: "Cảm giác thực tế mạnh mẽ",
    answer2: "Trí tưởng tượng phong phú",
    type: "S",
  },
  {
    number: 59,
    question: "Bạn bị thu hút bởi",
    answer1: "Các nguyên tắc, nguyên lý cơ bản",
    answer2: "Các ngụ ý, hàm ý, ẩn ý",
    type: "N",
  },
  {
    number: 60,
    question: "Theo bạn, điều nào là tệ hơn",
    answer1: "Quá nồng nhiệt, thiết tha",
    answer2: "Quá khách quan",
    type: "T",
  },
  {
    number: 61,
    question: "Bạn đánh giá mình là người thế nào?",
    answer1: "Thiết thực, cứng đầu, ít bị chi phối bởi tình cảm",
    answer2: "Từ tâm, dễ mềm lòng, đa cảm",
    type: "F",
  },
  {
    number: 62,
    question: "Bạn thích tình huống nào hơn",
    answer1: "Tình huống rõ ràng, có kế hoạch, lịch trình",
    answer2: "Tình huống tình cờ, ngẫu nhiên không có kế hoạch",
    type: "J",
  },
  {
    number: 63,
    question: "Bạn là người có xu hướng",
    answer1: "Theo thói quen, rập khuôn",
    answer2: "Dễ dàng thay đổi",
    type: "P",
  },
  {
    number: 64,
    question: "Bạn là người",
    answer1: "Dễ tiếp cận",
    answer2: "Hơi dè dặt, kín đáo",
    type: "E",
  },
  {
    number: 65,
    question: "Khi viết thì bạn thích",
    answer1: "Viết theo hướng văn chương, ý nghĩa hơn",
    answer2: "Viết theo số liệu, dữ liệu, hình tượng hơn",
    type: "N",
  },
  {
    number: 66,
    question: "Điều khiến bạn cảm thấy khó thực hiện hơn",
    answer1: "Hiểu và chia sẻ với người khác",
    answer2: "Sử dụng người khác",
    type: "F",
  },
  {
    number: 67,
    question: "Bạn mong muốn mình sẽ có thêm",
    answer1: "Lí trí suy xét rõ ràng",
    answer2: "Tình thương, lòng trắc ẩn sâu sắc",
    type: "T",
  },
  {
    number: 68,
    question: "Điều gì sẽ là lỗi lớn hơn",
    answer1: "Hành động bừa bãi, không cân nhắc",
    answer2: "Hành động chỉ trích, phê phán",
    type: "P",
  },
  {
    number: 69,
    question: "Bạn sẽ thích",
    answer1: "Sự kiện có kế hoạch trước",
    answer2: "Sự kiện không có kế hoạch trước",
    type: "J",
  },
  {
    number: 70,
    question: "Bạn có xu hướng hành động",
    answer1: "Cân nhắc thận trọng",
    answer2: "Tự nhiên, tự phát",
    type: "P",
  }
]
  